#! /bin/sh
### BEGIN INIT INFO
# Provides:          adc_IO14-IO15-IO16-IO17_continuous
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: It configures GPIO and ADCs (A0-IO14, A1-IO15, A2-IO16, A3-IO17).
# Description:       Levindo Neto and Vinicius Fratin - 18/2.
### END INIT INFO

case "$1" in
    start|restart|force-reload)
    # gpio49 = in = neither pull-up nor pull-down  >> A0 << Potentiometer >>
    if [ ! -d /sys/class/gpio/gpio49 ] ; then
        echo -n "49" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio49/direction

    # gpio51 = in = neither pull-up nor pull-down  >> A1 <<
    if [ ! -d /sys/class/gpio/gpio51 ] ; then
        echo -n "51" > /sys/class/gpio/export
    fi
        echo -n "in" > /sys/class/gpio/gpio51/direction

    # gpio53 = in = neither pull-up nor pull-down  >> A2 <<
    if [ ! -d /sys/class/gpio/gpio53 ] ; then
        echo -n "53" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio53/direction

    # gpio55 = in = neither pull-up nor pull-down  >> A3 <<
    if [ ! -d /sys/class/gpio/gpio55 ] ; then
        echo -n "55" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio55/direction

    # Add needed permissions for each all ADC connections from
    for i in {0..3} ; do
        chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage"$i"_scale
        chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage"$i"_scale
        chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage"$i"_en
        chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage"$i"_en
    done;

    chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
    chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en

    chgrp adc /sys/bus/iio/devices/iio:device0/buffer/enable
    chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/enable

    chgrp adc /sys/bus/iio/devices/iio:device0/buffer/length
    chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/length

    modprobe iio-trig-sysfs
    echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/add_trigger

    chgrp adc /sys/bus/iio/devices/trigger0/trigger_now
    chmod g+w /sys/bus/iio/devices/trigger0/trigger_now

    modprobe iio-trig-hrtimer
    echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/add_trigger

    chgrp adc /sys/bus/iio/devices/trigger1/frequency
    chmod g+rw /sys/bus/iio/devices/trigger1/frequency

    chgrp adc /sys/bus/iio/devices/iio:device0/trigger/current_trigger
    chmod g+rw /sys/bus/iio/devices/iio:device0/trigger/current_trigger

    chgrp adc /dev/iio:device0
    chmod g+r /dev/iio:device0
    ;;
    stop)

    echo "\n" > /sys/bus/iio/devices/iio:device0/trigger/current_trigger

    echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/remove_trigger
    rmmod iio-trig-hrtimer
    echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/remove_trigger
    rmmod iio-trig-sysfs

    echo -n "49" > /sys/class/gpio/unexport
    echo -n "51" > /sys/class/gpio/unexport
    echo -n "53" > /sys/class/gpio/unexport
    echo -n "55" > /sys/class/gpio/unexport
    ;;
    status)
    cat /sys/bus/iio/devices/iio:device0/trigger/current_trigger
    ;;
    *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
