#! /bin/sh
### BEGIN INIT INFO
# Provides:          adc_IO14_oneshot
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures GPIO and ADC for using ADC0 (IO14) in the One-Shot mode.
# Description:       Levindo Neto and Vinicius Fratin - 18/2.
### END INIT INFO

case "$1" in
    start|restart|force-reload)
    # ADC0: 22K RESISTOR -> gpio49 => Neither pull-down nor pull-up (dir: in, no value)
    if [ ! -d /sys/class/gpio/gpio49 ] ; then
        echo -n "49" > /sys/class/gpio/export
    fi
    echo -n "in" > /sys/class/gpio/gpio49/direction

    # Permission to in_voltage0_raw and in_voltage0_scale to have one-shot mode
    chgrp examgroup /sys/bus/iio/devices/iio:device0/in_voltage0_raw
    chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
    chgrp examgroup /sys/bus/iio/devices/iio:device0/in_voltage0_scale
    chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale
    ;;
    stop)

    echo -n "49" > /sys/class/gpio/unexport # Unexport 22k resistor
    ;;
    status)
    ;;
    *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
