#! /bin/sh
### BEGIN INIT INFO
# Provides:          config
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Configures the Galileo for the Servomotor Controller.
# Description:       Configures the Galileo for the Servomotor Controller.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

    #******** CONFIGURE D4 (I04) -> PUSHBUTTON (INTERRUPTION MODE) ************#
    # IO4 = gpio6
	if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    echo -n "6" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio6/direction
	chgrp gpio /sys/class/gpio/gpio6/value
	chmod g+r /sys/class/gpio/gpio6/value
	chgrp gpio /sys/class/gpio/gpio6/edge
	chmod g+rw /sys/class/gpio/gpio6/edge

	# gpio36 = 1 => IO4=in
	if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    echo -n "36" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio36/direction
	echo -n "1" > /sys/class/gpio/gpio36/value

	# gpio37 = 0 => pull-down
	if [ ! -d /sys/class/gpio/gpio37 ] ; then
	    echo -n "37" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio37/direction
	echo -n "0" > /sys/class/gpio/gpio37/value
    #----------------------------------------------------------------#

    #************ CONFIGURE LCD DISPLAY -> I2C **********************#
	# Pull-up on IO18
	if [ ! -d /sys/class/gpio/gpio57 ] ; then
    		echo -n "57" > /sys/class/gpio/export
	fi
	echo "out" > /sys/class/gpio/gpio57/direction
	echo "1" > /sys/class/gpio/gpio57/value

	# Select I2C on IO18 and IO19
	if [ ! -d /sys/class/gpio/gpio60 ] ; then
    		echo -n "60" > /sys/class/gpio/export
	fi
	echo "out" > /sys/class/gpio/gpio60/direction
	echo "0" > /sys/class/gpio/gpio60/value

	# Pull-up on IO19
	if [ ! -d /sys/class/gpio/gpio59 ] ; then
    		echo -n "59" > /sys/class/gpio/export
	fi
	echo "out" > /sys/class/gpio/gpio59/direction
	echo "1" > /sys/class/gpio/gpio59/value

    # Give permissions to the i2c pseudofiles
	chgrp i2c /dev/i2c-0
	chmod g+rw /dev/i2c-0
	;;
    stop)
    #************ UNEXTPORT I2C -> LCD DISPLAY **********************#
    # No pull-up on IO18
	echo "in" > /sys/class/gpio/gpio57/direction
	ecbo "57" > /sys/class/gpio/unexport
	# GPIO on IO18 and IO19
	echo "1" > /sys/class/gpio/gpio60/value
	echo "60" > /sys/class/gpio/unexport
	# No pull-up on  IO19
	echo "in" > /sys/class/gpio/gpio59/direction
	echo "59" > /sys/class/gpio/unexport
    #----------------------------------------------------------------#

    #***** UNEXTPORT D4 (I04) -> PUSHBUTTON (INTERRUPTION MODE) *****#
    echo -n "in" > /sys/class/gpio/gpio37/direction
    echo -n "37" > /sys/class/gpio/unexport
    echo -n "36" > /sys/class/gpio/unexport
    echo -n "6" > /sys/class/gpio/unexport
    #----------------------------------------------------------------#

    ;;
    status)
    ls -d /sys/class/gpio/gpio*
	;;
    *)
	echo -n "Usage: $0 "
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
