#! /bin/sh
### BEGIN INIT INFO
# Provides:          eeprom
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: It configures the Galileo's eeprom.
# Description:       Levindo Neto and Vinicius Fratin - 18/2.
### END INIT INFO

case "$1" in
    start|restart|force-reload)
    # Permissions for users of the examgroup to access the eeprom
    chgrp examgroup /sys/bus/i2c/devices/0-0054/eeprom
    chmod g+rw /sys/bus/i2c/devices/0-0054/eeprom
    ;;
    stop)
    ;;
    status)
    ;;
    *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
