#! /bin/sh
### BEGIN INIT INFO
# Provides:          io7_data
# Required-Start:
# Should-Start:

# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: It configures the IO7 - DATA
# Description:       Levindo Neto and Vinicius Fratin - 18/2.
### END INIT INFO
case "$1" in
    start|restart|force-reload)
    # IO7: LINUX -> gpio38
    if [ ! -d /sys/class/gpio/gpio38 ] ; then
        echo -n "38" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio38/direction

    # gpio39 = 0 => pull-down
    if [ ! -d /sys/class/gpio/gpio39 ] ; then
        echo -n "39" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio39/direction
    echo -n "0" > /sys/class/gpio/gpio39/value

    # Give permissions to the members of examgroup to access the gpio 13
    chgrp examgroup /sys/class/gpio/gpio38/value
    chmod g+rw /sys/class/gpio/gpio38/value

    ;;
    stop)
    # Put gpio1 to dir_in for avoiding short circuits
    echo -n "in" > /sys/class/gpio/gpio0/direction
    echo -n "38" > /sys/class/gpio/unexport # Unexport linux
    echo -n "39" > /sys/class/gpio/unexport # Unexport linux
    ;;
    status)
        ls -d /sys/class/gpio/gpio*
    ;;
    *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
