#! /bin/sh
### BEGIN INIT INFO
# Provides:          lcd_I2C
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: It configures the Galileo's shield pins for using the I2C (LCD of the grove kit).
# Description:       Levindo Neto and Vinicius Fratin - 18/2.
### END INIT INFO

case "$1" in
    start|restart|force-reload)

    # I2C-0 (I2C SDA - IO18): 22K RESISTOR -> gpio57 => pull-up (dir: out, value: 1)
    if [ ! -d /sys/class/gpio/gpio57 ] ; then
        echo -n "57" > /sys/class/gpio/export
    fi
    echo "out" > /sys/class/gpio/gpio57/direction
    echo "1" > /sys/class/gpio/gpio57/value

    # I2C-0: PIN MUX -> 1 GPIO: gpio60(L), L: out, 0 (selected on IO18 and IO19)
    if [ ! -d /sys/class/gpio/gpio60 ] ; then
        echo -n "60" > /sys/class/gpio/export
    fi
    echo "out" > /sys/class/gpio/gpio60/direction
    echo "0" > /sys/class/gpio/gpio60/value

    # I2C-0 (I2C SCL - IO19): 22K RESISTOR -> gpio59 => pull-up (dir: out, value: 1)
    if [ ! -d /sys/class/gpio/gpio59 ] ; then
        echo -n "59" > /sys/class/gpio/export
    fi
    echo "out" > /sys/class/gpio/gpio59/direction
    echo "1" > /sys/class/gpio/gpio59/value

    # Permissions for users of the examgroup to access the i2c
    chgrp examgroup /dev/i2c-0
    chmod g+rw /dev/i2c-0
    ;;
    stop)

    # Unexport IO18's 22k pull-up resistor
    echo "in" > /sys/class/gpio/gpio57/direction
    echo "57" > /sys/class/gpio/unexport

    # Unexport pin mux (1_gpio)
    echo "1" > /sys/class/gpio/gpio60/value
    echo "60" > /sys/class/gpio/unexport

    # Unexport IO19's 22k pull-up resistor
    echo "in" > /sys/class/gpio/gpio59/direction
    echo "59" > /sys/class/gpio/unexport
    ;;
    status)
    ;;
    *)
    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
