#! /bin/sh
### BEGIN INIT INFO
# Provides:         pwm3_IO5
# Required-Start:
# Should-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: It configures the IO5 as PWM3.
# Description:       Levindo Neto and Vinicius Fratin - 18/2.
### END INIT INFO

case "$1" in
    start|restart|force-reload)
    # Set PWM_3
    if [ ! -d /sys/class/pwm/pwmchip0/pwm3 ] ; then
        echo -n "3" > /sys/class/pwm/pwmchip0/export
    fi

    # Permissions for using the Galileo's PWM (examgroup's members)
    chgrp examgroup /sys/class/pwm/pwmchip0/device/pwm_period
    chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period
    chgrp examgroup /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    chmod g+w /sys/class/pwm/pwmchip0/pwm3/duty_cycle
    chgrp examgroup /sys/class/pwm/pwmchip0/pwm3/enable
    chmod g+w /sys/class/pwm/pwmchip0/pwm3/enable

    # IO3_PWM1: PIN MUX -> 1 GPIO: gpio66(L) - No direction needed
    if [ ! -d /sys/class/gpio/gpio66 ] ; then
        echo -n "66" > /sys/class/gpio/export
    fi
    echo -n "1" > /sys/class/gpio/gpio66/value

    # IO3_PWM3: LEVEL_SHIFTER -> gpio18 => dir_out [L] (out, 0)
    if [ ! -d /sys/class/gpio/gpio18 ] ; then
        echo -n "18" > /sys/class/gpio/export
    fi
    echo -n "out" > /sys/class/gpio/gpio18/direction
    echo -n "0" > /sys/class/gpio/gpio18/value

    # IO3_PWM1: 22K RESISTOR -> gpio19 => Neither pull-down nor pull-up (dir: in, no value)
    if [ ! -d /sys/class/gpio/gpio19 ] ; then
        echo -n "19" > /sys/class/gpio/export
    fi
    # Set gpio17 back to in to avoid short circuits
    echo -n "in" > /sys/class/gpio/gpio19/direction
    ;;
    stop)

    echo -n "0" > /sys/class/pwm/pwmchip0/pwm3/enable # Unable PWM_3
    echo -n "66" > /sys/class/gpio/unexport # Unexport pin mux (1_gpio)
    echo -n "19" > /sys/class/gpio/unexport # Unexport 22K Resistor
    echo -n "1" > /sys/class/gpio/gpio18/value # level shifter -> in
    echo -n "18" > /sys/class/gpio/unexport # Unexport level shifter
    echo -n "3" > /sys/class/pwm/pwmchip0/unexport # Unexport pwn_3
    ;;
    status)

    # Debugging stuff
	echo -n Period:
	cat /sys/class/pwm/pwmchip0/device/pwm_period
	echo -n Duty Cicle:
	cat /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	echo -n Enable:
	cat /sys/class/pwm/pwmchip0/pwm1/enable
    ;;
    *)

    echo -n "Usage: $0 "
    echo "{start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
